'use strict';
/* Brainteasers d'entretien (finance / conseil / trading) — réponses entières. */
A.TEASERS = [
  { id: 't01', q: 'Combien de fois les aiguilles des heures et des minutes se superposent-elles en 24 h ?', a: 22, e: '11 fois toutes les 12 h (pas à 11 h pile : la superposition suivante est à midi).' },
  { id: 't02', q: 'Combien de zéros à la fin de 100! ?', a: 24, e: 'On compte les facteurs 5 : ⌊100/5⌋ + ⌊100/25⌋ = 20 + 4.' },
  { id: 't03', q: 'Une batte et une balle coûtent 1,10 € ensemble. La batte coûte 1 € de plus que la balle. Prix de la balle, en centimes ?', a: 5, e: 'b + (b + 1) = 1,10 → b = 0,05 €. (10 centimes est le piège.)' },
  { id: 't04', q: '100 casiers fermés. Le passage k inverse l’état des casiers multiples de k (k = 1…100). Combien restent ouverts ?', a: 10, e: 'Seuls les carrés parfaits ont un nombre impair de diviseurs : 1, 4, 9 … 100.' },
  { id: 't05', q: 'Combien de carrés (toutes tailles) sur un échiquier 8×8 ?', a: 204, e: '1² + 2² + … + 8² = 204.' },
  { id: 't06', q: 'Combien de rectangles (carrés compris) sur un échiquier 8×8 ?', a: 1296, e: 'Choisir 2 lignes verticales et 2 horizontales parmi 9 : C(9,2)² = 36².' },
  { id: 't07', q: '20 personnes se serrent toutes la main une fois. Combien de poignées de main ?', a: 190, e: 'C(20,2) = 20 × 19 / 2.' },
  { id: 't08', q: 'Tournoi à élimination directe avec 100 joueurs. Combien de matchs pour désigner le vainqueur ?', a: 99, e: 'Chaque match élimine exactement un joueur : il faut en éliminer 99.' },
  { id: 't09', q: 'Un nénuphar double de surface chaque jour et couvre le lac au 48e jour. Quel jour couvrait-il la moitié du lac ?', a: 47, e: 'La veille du jour où il le couvre entièrement.' },
  { id: 't10', q: '5 machines font 5 pièces en 5 minutes. Combien de minutes pour que 100 machines fassent 100 pièces ?', a: 5, e: 'Une machine fait une pièce en 5 minutes, quel que soit leur nombre.' },
  { id: 't11', q: 'Combien de chiffres faut-il pour numéroter les pages d’un livre de 1 à 100 ?', a: 192, e: '9 × 1 + 90 × 2 + 1 × 3 = 192.' },
  { id: 't12', q: 'Combien de fois le chiffre 7 apparaît-il en écrivant les nombres de 1 à 100 ?', a: 20, e: '10 fois en unités (7, 17 … 97) + 10 fois en dizaines (70 … 79).' },
  { id: 't13', q: 'Angle (en degrés) entre les aiguilles à 4 h 20 ?', a: 10, e: 'Minutes : 120°. Heures : 4 × 30 + 20 × 0,5 = 130°. Écart : 10°.' },
  { id: 't14', q: 'Somme des 50 premiers nombres impairs ?', a: 2500, e: '1 + 3 + … + (2n − 1) = n² = 50².' },
  { id: 't15', q: 'Combien de diagonales dans un décagone (10 côtés) ?', a: 35, e: 'n(n − 3)/2 = 10 × 7 / 2.' },
  { id: 't16', q: 'Un escargot au fond d’un puits de 10 m monte de 3 m le jour et glisse de 2 m la nuit. Le combientième jour sort-il ?', a: 8, e: 'Après 7 nuits il est à 7 m ; le 8e jour il monte à 10 m et sort.' },
  { id: 't17', q: 'Un tiroir contient 10 chaussettes noires et 10 blanches. Combien en tirer (dans le noir) pour être sûr d’avoir une paire ?', a: 3, e: 'Deux couleurs : la 3e chaussette forme forcément une paire.' },
  { id: 't18', q: 'Même tiroir. Combien en tirer pour être sûr d’avoir 2 chaussettes NOIRES ?', a: 12, e: 'Pire cas : les 10 blanches d’abord, puis 2 noires.' },
  { id: 't19', q: 'Une action baisse de 50 % puis monte de 50 %. Perte totale en % ?', a: 25, e: '0,5 × 1,5 = 0,75.' },
  { id: 't20', q: 'Une action fait +10 % puis −10 %. Perte totale en % ?', a: 1, e: '1,1 × 0,9 = 0,99.' },
  { id: 't21', q: 'Combien de zéros à la fin de 50! ?', a: 12, e: '⌊50/5⌋ + ⌊50/25⌋ = 10 + 2.' },
  { id: 't22', q: 'À partir de combien de personnes la probabilité que deux partagent un anniversaire dépasse-t-elle 50 % ?', a: 23, e: 'Paradoxe des anniversaires : 1 − ∏(365 − k)/365 > 0,5 dès 23.' },
  { id: 't23', q: 'Combien d’anagrammes du mot TRADER ?', a: 360, e: '6! / 2! (le R apparaît deux fois).' },
  { id: 't24', q: 'Combien de mains de 5 cartes différentes avec un jeu de 52 ?', a: 2598960, e: 'C(52,5) = 2 598 960.' },
  { id: 't25', q: 'Somme des angles intérieurs d’un hexagone (en degrés) ?', a: 720, e: '(n − 2) × 180 = 4 × 180.' },
  { id: 't26', q: 'Deux trains à 300 km l’un de l’autre roulent l’un vers l’autre à 60 et 90 km/h. Dans combien de minutes se croisent-ils ?', a: 120, e: 'Vitesse relative 150 km/h → 2 h.' },
  { id: 't27', q: 'Combien de nombres premiers inférieurs à 50 ?', a: 15, e: '2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47.' },
  { id: 't28', q: 'Espérance de la somme de 10 dés ?', a: 35, e: 'Linéarité : 10 × 3,5.' },
  { id: 't29', q: 'Suite : 1, 11, 21, 1211, 111221, … Terme suivant ?', a: 312211, e: 'On lit le terme précédent : « trois 1, deux 2, un 1 ».' },
  { id: 't30', q: 'Combien de fois le chiffre 1 apparaît-il de 1 à 100 ?', a: 21, e: '10 en unités, 10 en dizaines (10–19), + 1 dans 100.' },
  { id: 't31', q: 'Nombre à 2 chiffres : la somme de ses chiffres vaut 10 et, si on ajoute 18, ses chiffres s’inversent. Lequel ?', a: 46, e: '+18 inverse les chiffres ⇒ b = a + 2 ; a + b = 10 ⇒ 46.' },
  { id: 't32', q: 'Un père a 3 fois l’âge de son fils. Dans 15 ans, il aura le double. Âge du fils ?', a: 15, e: '3x + 15 = 2(x + 15) ⇒ x = 15.' },
  { id: 't33', q: 'Tu gagnes le résultat d’un dé (en €), avec droit à UNE relance. Valeur du jeu en centimes ?', a: 425, e: 'Relance si 1, 2 ou 3 : ½ × 5 + ½ × 3,5 = 4,25 €.' },
  { id: 't34', q: 'Combien d’entiers entre 1 et 1000 sont divisibles par 3 ou par 5 ?', a: 467, e: '333 + 200 − 66 (divisibles par 15).' },
  { id: 't35', q: 'Combien de sous-ensembles (vide compris) pour un ensemble de 10 éléments ?', a: 1024, e: '2^10 : chaque élément est dedans ou pas.' },
  { id: 't36', q: 'Chemins d’un coin à l’autre d’une grille 4×4 en n’allant qu’à droite ou en haut ?', a: 70, e: '8 pas dont 4 à droite : C(8,4).' },
  { id: 't37', q: 'Monty Hall : en changeant de porte, probabilité de gagner, en % (arrondi) ?', a: 67, accept: [66, 67], e: '2/3 : tu gagnes dès que ton premier choix était perdant.' },
  { id: 't38', q: '3 fourmis aux sommets d’un triangle partent chacune sur une arête au hasard. Probabilité (en %) qu’aucune ne se croise ?', a: 25, e: 'Seuls « tous horaire » ou « tous anti-horaire » marchent : 2/8.' },
  { id: 't39', q: 'Une brique pèse 1 kg plus une demi-brique. Poids d’une brique en kg ?', a: 2, e: 'b = 1 + b/2 ⇒ b = 2.' },
  { id: 't40', q: 'Combien de carrés parfaits entre 1 et 1000 ?', a: 31, e: '31² = 961 et 32² = 1024.' },
  { id: 't41', q: 'Combien de zéros à la fin de 1000! ?', a: 249, e: '200 + 40 + 8 + 1 (divisions par 5, 25, 125, 625).' },
  { id: 't42', q: '3 chats attrapent 3 souris en 3 minutes. Combien de chats pour attraper 100 souris en 100 minutes ?', a: 3, e: 'Chaque chat attrape une souris en 3 minutes : 3 chats × 33 souris.' },
  { id: 't43', q: 'Combien de fois par jour les aiguilles d’une horloge forment-elles un angle droit ?', a: 44, e: '22 fois toutes les 12 h.' },
  { id: 't44', q: '8 billes dont une plus lourde, une balance à deux plateaux. Nombre minimal de pesées pour la trouver à coup sûr ?', a: 2, e: 'Pèse 3 contre 3 : on isole un groupe de 3 (ou 2), puis 1 contre 1.' },
  { id: 't45', q: '12 billes dont une différente (plus lourde OU plus légère). Nombre minimal de pesées ?', a: 3, e: '3 pesées donnent 27 issues ≥ 24 cas possibles : c’est le minimum atteignable.' },
  { id: 't46', q: '25 chevaux, des courses de 5, pas de chrono. Nombre minimal de courses pour trouver les 3 plus rapides ?', a: 7, e: '5 courses de groupes + 1 des gagnants + 1 finale des 5 candidats restants.' },
  { id: 't47', q: 'Somme 1 + 2 + 4 + 8 + … + 512 ?', a: 1023, e: 'Somme géométrique : 2^10 − 1.' },
  { id: 't48', q: 'Un livre coûte 10 € plus la moitié de son prix. Prix du livre ?', a: 20, e: 'p = 10 + p/2 ⇒ p = 20.' },
  { id: 't49', q: 'Combien de triangles peut-on former avec les sommets d’un hexagone ?', a: 20, e: 'C(6,3) = 20.' },
  { id: 't50', q: 'Combien de zéros à la fin de 2^10 × 5^8 ?', a: 8, e: '= 2² × 10^8 = 400 000 000.' },
  { id: 't51', q: 'La moyenne de 5 nombres vaut 20. On en retire un : la moyenne passe à 18. Nombre retiré ?', a: 28, e: '100 − 4 × 18 = 28.' },
  { id: 't52', q: 'Combien de secondes dans une journée ?', a: 86400, e: '24 × 3600.' },
  { id: 't53', q: '100 € placés à 10 % par an, intérêts composés. Valeur après 2 ans, en € ?', a: 121, e: '100 × 1,1².' },
  { id: 't54', q: 'Règle de 72 : en combien d’années un placement à 8 % par an double-t-il (environ) ?', a: 9, e: '72 / 8 = 9 (valeur exacte ≈ 9,0).' },
  { id: 't55', q: 'Un portefeuille perd 20 %. Quelle hausse en % faut-il pour revenir au départ ?', a: 25, e: '0,8 × 1,25 = 1.' }
];
A.dailyTeaser = day => {
  const all = A.TEASERS, open = all.filter(t => !(A.db.teasers[t.id] && A.db.teasers[t.id].ok));
  const pool = open.length ? open : all;
  return pool[A.hash('tz' + day) % pool.length];
};
